language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lior/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true lior/react-docker  npm run test -- --coverage
