version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    container_name: aa
    image: a/a
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - /app/node_modules
        - .:/app
    container_name: aa_test
    image: a/a_test
    command: ['npm','run','test']